-- CHARACTER TYPES

SELECT ('Lorem'::CHAR(10));

SELECT ('Lorem ipsum dolor sit amet'::CHAR(10));

SELECT ('Lorem'::VARCHAR(10));

SELECT ('Lorem ipsum dolor sit amet'::VARCHAR(10));

SELECT ('Lorem ipsum dolor sit amet'::VARCHAR);

SELECT ('Lorem'::TEXT);

SELECT ('Lorem ipsum dolor sit amet'::TEXT);

-- BOOLEAN TYPES

-- TRUE
SELECT (true);
SELECT (TRUE);
SELECT ('yes'::BOOLEAN);
SELECT ('YES'::BOOLEAN);
SELECT ('t'::BOOLEAN);
SELECT ('T'::BOOLEAN);
SELECT (1::BOOLEAN);
SELECT ((3-2)::BOOLEAN);
SELECT ((3>2)::BOOLEAN);
SELECT ('on'::BOOLEAN);
SELECT ('ON'::BOOLEAN);

-- FALSE
SELECT (false);
SELECT (FALSE);
SELECT ('no'::BOOLEAN);
SELECT ('NO'::BOOLEAN);
SELECT ('f'::BOOLEAN);
SELECT ('F'::BOOLEAN);
SELECT (0::BOOLEAN);
SELECT ((3-3)::BOOLEAN);
SELECT ((3<=2)::BOOLEAN);
SELECT ('off'::BOOLEAN);
SELECT ('OFF'::BOOLEAN);

-- NULL
SELECT (null::BOOLEAN);
SELECT (NULL::BOOLEAN);

-- DATE TIME TYPES

SELECT ('1980-12-03'::DATE);
SELECT ('DEC-03-1980'::DATE);
SELECT ('DEC 03 1980'::DATE);
SELECT ('1980 December 03'::DATE);

SELECT ('03:44'::TIME);
SELECT ('03:44 AM'::TIME);
SELECT ('03:44 PM'::TIME);
SELECT ('03:44:11'::TIME);
SELECT ('02:16'::TIME WITH TIME ZONE);

SELECT ('1980 December 03 02:16:09'::TIMESTAMP);
SELECT ('1980 December 03 02:16:09'::TIMESTAMP WITH TIME ZONE);